package software.amazon.globalaccelerator.crossaccountattachment

import com.amazonaws.services.globalaccelerator.model.DescribeCrossAccountAttachmentRequest
import com.amazonaws.services.globalaccelerator.model.DescribeCrossAccountAttachmentResult
import com.amazonaws.services.globalaccelerator.model.UpdateCrossAccountAttachmentRequest
import com.amazonaws.services.globalaccelerator.model.UpdateCrossAccountAttachmentResult
import com.amazonaws.services.globalaccelerator.model.CreateCrossAccountAttachmentRequest
import com.amazonaws.services.globalaccelerator.model.CreateCrossAccountAttachmentResult
import com.amazonaws.services.globalaccelerator.model.DeleteCrossAccountAttachmentRequest
import com.amazonaws.services.globalaccelerator.model.DeleteCrossAccountAttachmentResult
import com.amazonaws.services.globalaccelerator.model.ListCrossAccountAttachmentsRequest
import com.amazonaws.services.globalaccelerator.model.ListCrossAccountAttachmentsResult
import com.amazonaws.services.globalaccelerator.model.TagResourceRequest
import com.amazonaws.services.globalaccelerator.model.TagResourceResult
import com.amazonaws.services.globalaccelerator.model.UntagResourceRequest
import com.amazonaws.services.globalaccelerator.model.UntagResourceResult
import java.util.function.Function

typealias ProxyDescribeCrossAccountAttachment = Function<DescribeCrossAccountAttachmentRequest, DescribeCrossAccountAttachmentResult>
typealias ProxyUpdateCrossAccountAttachment = Function<UpdateCrossAccountAttachmentRequest, UpdateCrossAccountAttachmentResult>
typealias ProxyCreateCrossAccountAttachment = Function<CreateCrossAccountAttachmentRequest, CreateCrossAccountAttachmentResult>
typealias ProxyDeleteCrossAccountAttachment = Function<DeleteCrossAccountAttachmentRequest, DeleteCrossAccountAttachmentResult>
typealias ProxyListCrossAccountAttachment = Function<ListCrossAccountAttachmentsRequest, ListCrossAccountAttachmentsResult>
typealias ProxyTagCrossAccountAttachment = Function<TagResourceRequest, TagResourceResult>
typealias ProxyUntagCrossAccountAttachment = Function<UntagResourceRequest, UntagResourceResult>
