AWSTemplateFormatVersion: "2010-09-09"
Description: Listener Dependencies

Resources:
  ListenerAccelerator:
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      Name: CFNListenerAccelerator
      IpAddressType: IPV4

Outputs:
  ListenerAcceleratorArn:
    Value:
      Fn::GetAtt: [ListenerAccelerator, AcceleratorArn]
    Export:
      Name: awsglobalacceleratorlistenercto1
